site_name: Shared Vision Documentation
site_url: https://example.com
nav:
  - Home: index.md
  - Sharing Options: sharingOptions.md
  - Module Settings: moduleSettings.md
  - Vision Config: visionConfig.md
  - Control Buttons: controlButtons.md
  - Other Modules: otherModules.md
  
theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    
  features:
    - navigation.tracking
    #- navigation.tabs
    - toc.integrate
    #- navigation.top
plugins:
  - search
markdown_extensions:
  - attr_list
extra_css: []